---
remove_cloud_user: true

#custom_packages:
  #gcc: {}

custom_users:
  raymond: {}

custom_sudoers:
  raymond: {}

custom_authorized_keys:
  raymond@work:
    user: raymond
    key:  'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILmS01dwnGoQcxjR0ZNqSP1e5nRK43buD0rqd4sNkmbu raymond@uib.no'
  raymond@home:
    key:  'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGh8ABoo3nkFSAlTTiWqcTmqUp98uPJP/wNvQzMTsvJ6 raymond@home'
    user: raymond

