---
nvim_install_nerdfonts: true

remove_cloud_user: false

custom_packages:
  awesome: {}
  awesome-extra: {}
  whois: {}
  vagrant: {}
  packer: {}
  terraform: {}
  python3-openstackclient: {}
  brave-browser: {}
  signal-desktop: {}
  tree: {}
  mlocate: {}
  net-tools: {}
  gh: {}
  insync: {}
  keychain: {}
  xscreensaver: {}
  virt-manager: {}
  virtualbox-7.0: {}
  build-essential: {}
  gcc-12: {}
  teams-for-linux: {}

custom_users:
  st02221: {}

custom_sudoers: {}

custom_apt_repos:
  hashicorp:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
  brave-browser:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
  signal:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
  gh-cli:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
  virtualbox:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/virtualbox-keyring-2016.gpg] https://download.virtualbox.org/virtualbox/debian jammy contrib"
  teamsforlinux:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/teams-for-linux-keyring.gpg] https://repo.teamsforlinux.de/debian/ stable main"
  insync:
    repo: "deb http://apt.insync.io/ubuntu jammy non-free contrib"

custom_apt_keys:
  hashicorp:
    url: 'https://apt.releases.hashicorp.com/gpg'
    id: '798AEC654E5C15428C8E42EEAA16FCBCA621E701'
    keyring: '/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg'
  brave-browser:
    url: 'https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
    id: 'DBF1A116C220B8C7164F98230686B78420038257'
    keyring: '/etc/apt/trusted.gpg.d/brave-browser-archive-keyring.gpg'
  signal:
    url: 'https://updates.signal.org/desktop/apt/keys.asc'
    id: 'DBA36B5181D0C816F630E889D980A17457F6FB06'
    keyring: '/etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg'
  gh-cli:
    url: 'https://cli.github.com/packages/githubcli-archive-keyring.gpg'
    id: '23F3D4EA75716059'
    keyring: '/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg'
  virtualbox:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    id: 'B9F8D658297AF3EFC18D5CDFA2F683C52980AECF'
    keyring: '/etc/apt/trusted.gpg.d/virtualbox-keyring-2016.gpg'
  teamsforlinux:
    url: 'https://repo.teamsforlinux.de/teams-for-linux.asc'
    id: 'D112747BDF6269C845972E5C2FD80E00E6A6E47D'
    keyring: '/etc/apt/trusted.gpg.d/teams-for-linux-keyring.gpg'
  insync:
    id: 'ACCAF35C'
    keyserver: 'keyserver.ubuntu.com'

custom_authorized_keys:
  raymond@work:
    user: st02221
    key:  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdT7QHIcmvOtNiTJI8emS0E8YGohzw4tpNKI5VkgY4oPzwcXHKNW+4FNViO+2ikBhf0seGPxtKUlpf0jBfUkMRb95GtzWPQSAOtyGihn4CsQs2mWekwE8jOILJTc6Pi8ht92ai7DSc1Nnv6Uss28rgLoSI9PAo3nXNZEYhG5shJS+Ks1Ut0xw0NT2D/ZYIihMXk2xwbraIYq99xUKJ7zKPHCW/1mMba5gtPTk27Q4wWX5yg+TuBpsvqyKMj1/sJ2KY0dmZhVvFhFMpAUoC5AYxryUXepksYnIiQ5hPUI6oCTLIoV8i67kVfL2FgvX7IkDrrAUw3M2MnPJa63gDXPVUNjJE2v/5/4Ik66N1AE04Jdb8FrplSogG525uSIda3saMoV6R+krlV0UBwml1beaBUHWodKu/ML1CMU1Lpb/vAg2ylIbBQByR/pxGPVeUD001ACb2bUMJmco62468nu27vHiY08QqRpav13wtMxqITGGYsMYslosIwHqd91BYCDVqF1OgfSTYTqBH2SZZcJVpChOSAIB4quBMkIOFwnFpG+mSrEpbprKg5BNXSMIXTiMFb/SH2+r+rNvbY+ssCs+CwjpDdO8PS4W1v3AHXZFrORP7meQR4Xd9mOvsPeMh63UscMpNsGvTentOhunacf6uhkTKut/3skxmlLyiiIPKPQ==  st02221@it010212'
  raymond@home:
    key:  'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGh8ABoo3nkFSAlTTiWqcTmqUp98uPJP/wNvQzMTsvJ6 raymond@home'
    user: st02221


sshd:
  GSSAPIAuthentication: 'no'
  X11Forwarding: 'yes'
  PasswordAuthentication: 'no'
  AllowAgentForwarding: 'yes'
  PermitRootLogin: 'no'
  AllowUsers: 
  - "st02221"
  - "{{ hostvars[inventory_hostname].ansible_ssh_user | default(omit) }}"
