---
roles:
  - name: common
    src: https://github.com/raykrist/ansible-common
    version: master

  - name: neovim
    src: https://github.com/raykrist/ansible-neovim
    version: master

  - name: sshd
    src: willshersystems.sshd
    version: v0.23.0

collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.2.0
