---
- src: willshersystems.sshd
  version: v0.6.2
  name: sshd
- src: andrewrothstein.terraform
  version: v2.2.10
  name: terraform
- src: https://github.com/raykrist/ansible-common
  version: master
  name: common
