---
roles:
  - name: common
    src: https://github.com/raykrist/ansible-common
    version: master

  - name: sshd
    src: willshersystems.sshd
    version: v0.20.0

collections:
  - name: ansible.posix
    version: 1.5.4
